const menuData = [
  {category:"Vorspeisen",items:[
    ["001","Kokoscreme-Suppe","Kokoscreme, Hühnerbrühe, Gemüse, Pilze und Kräuter. Wahlweise Tofu 4,90 €, Hühnerfleisch 4,90 € oder Garnelen 5,90 €.","G, M","ab 4,90 €"],
    ["002","Miso-Suppe","Sojabrühe, Seetang und Frühlingszwiebeln. Seidentofu 4,50 € oder Lachsstreifen und Seidentofu 4,90 €.","C, M","ab 4,50 €"],
    ["003","Wantan-Suppe","Klare Hühnerbrühe, Wan-Tan-Taschen aus Hühnerfleisch, Garnelen, Gemüse, Kräuter, Hühnerbrust, Wachteleier, Shiitake, Karotten und Klebreismehl.","","5,90 €"],
    ["004","Papaya Salat","Grüne Papaya, Sojasprossen, Karotten, Kräuter, Erdnüsse, Knoblauch, Chili und hausgemachtes Dressing. Vegan 6,50 €, Hühnerfleisch 7,50 €, Garnelen 8,50 €.","B, M, C","ab 6,50 €"],
    ["005","Mango Salat","Frische Mango, Karotten, Minze, Erdnüsse, Röstzwiebeln, Feldsalat, saisonal und hausgemachtes Dressing. Tofu 5,50 €, Hühnerfleisch 6,90 €, Garnelen 7,50 €, Ente 9,50 €.","B, M, C","ab 5,50 €"],
    ["006","Goi Cuon · Sommerrollen","Reispapier, Reisnudeln, Ei, Salat, Gurke, Karotten, Koriander, Mango, Erdnuss, Sesam und Hoisinsoße. Vegetarisch 4,50 €, Hühnerfleisch 4,90 €, Garnelen 5,90 €.","A, M","ab 4,50 €"],
    ["007","Salat Oktopus","Grüner Papayasalat mit gegrilltem Oktopus, Sesam, Erdnüssen, Limetten-Vinaigrette und Röstzwiebeln.","B, L, N","12,90 €"],
    ["008","Nem Ran · Frühlingsrollen","Traditionelle Frühlingsrollen, gefüllt mit Hackfleisch, Garnelen, Karotten, Morcheln und Glasnudeln.","E, M","4,90 €"],
    ["009","Tom Chien Com · Klebreisflocken","2 Tiger-Garnelen, umwickelt mit knusprigen Klebreisflocken, dazu hausgemachter Dip.","D, E","6,50 €"],
    ["010","Mini-Frühlingsrollen · 6 Stück","Vegetarische Frühlingsrollen mit Süßsauer-Soße.","A, D","4,50 €"],
    ["011","Vorspeise Set · Große Platte","Klebreisflocken-Garnelen, Mango-Salat, Sommerrollen und Wantan.","A, B, D, E, L, M, N","19,90 €"]
  ]},
  {category:"Japanische Vorspeisen",items:[
    ["012","Wantan Chien · Gebackene Wantan","5 knusprige Teigtaschen mit gebackenem Hühnerfleisch und Garnelen, dazu süßsaure Soße.","D, E","5,90 €"],
    ["013","Dimsum Teigtaschen","5 gedämpfte Teigtaschen mit verschiedenen Füllungen, süßsaurer Dip und Kürbis.","D","5,90 €"],
    ["014","Dau Edamame","Gedämpfte japanische Bohnen mit Meersalz.","M","4,90 €"],
    ["015","Wakame","Eingelegter Seetang-Salat mit Sesam.","M","5,20 €"],
    ["016","Kimchi-Salat","Eingelegter Chinakohl.","","5,90 €"],
    ["017","Gyoza · 5 Stück","Wahlweise Gemüse 5,90 € oder Hühnerfleisch 6,90 €.","D, M","ab 5,90 €"],
    ["018","Yakitori Ga Xien","3 gegrillte Hühnerspieße mit Teriyaki-Soße und Sesam.","M","6,90 €"],
    ["019","Salmon Tataki Lachs","Leicht gegrillter Lachs im Sesam-Mantel, Salat.","C","10,90 €"],
    ["020","Tatar","Fein gewürfelter roher Lachs oder Thunfisch, mariniert mit Gewürzen, Wakame und Kaviar.","C","ab 13,90 €"]
  ]},
  {category:"Nudelgerichte",items:[
    ["021","Pho · Reisbandnudel-Suppe","Traditionelle 12-Kräuter-Brühe mit Reisbandnudeln, Kräutern und Lauchzwiebeln. Chicken 11,90 €, Beef 12,50 €, Chicken & Beef 14,50 €.","M","ab 11,90 €"],
    ["022","Ramen Xao · Gebratene Ramen-Nudeln","Im Wok geschwenkte Ramen-Nudeln, Gemüse, Ei, Sojasprossen und Röstzwiebeln. Tofu 12,50 €, Chicken 13,50 €, Beef 13,50 €, Garnelen 15,50 €, Ente 15,90 €.","A, M","ab 12,50 €"],
    ["023","Bun Tron · Reisnudel-Salat","Reisnudeln, Salat, Karotten, Kräuter, hausgemachtes Dressing, Röstzwiebeln und Erdnüsse. Verschiedene Varianten.","B","ab 13,50 €"],
    ["024","Udon Xao · Gebratene Udon","Hausgemachte Curry-Soße mit Wok-Udon und Gemüse. Tofu 13,50 €, Hühnerfleisch 14,50 €, Rindfleisch 14,50 €, Garnelen 16,50 €, Ente 17,90 €, Lachs 17,90 €.","D, G","ab 13,50 €"]
  ]},
  {category:"Hauptspeisen",items:[
    ["025","Knuspriges Hähnchenfilet","Mit Jasminreis, Sesam, Gemüse, Salat und Soße nach Wahl.","","14,90 €"],["026","Knusprige Ente","Mit Jasminreis, Sesam, Gemüse, Salat und Soße nach Wahl.","","18,50 €"],["027","Lachs","Mit Jasminreis, Sesam, Gemüse, Salat und Soße nach Wahl.","","18,50 €"],["028","Gebratene Hühnerbrustfilet","Mit Jasminreis, Sesam, Gemüse, Salat und Soße nach Wahl.","","12,90 €"],["029","Gebratenes Rindfleisch","Mit Jasminreis, Sesam, Gemüse, Salat und Soße nach Wahl.","","13,90 €"],["030","Garnelen","Mit Jasminreis, Sesam, Gemüse, Salat und Soße nach Wahl.","","15,50 €"],["031","Tofu","Mit Jasminreis, Sesam, Gemüse, Salat und Soße nach Wahl.","","12,50 €"],["032","Gebratener Reis","Mit Gemüse. Veggie 10,90 €, Hühnerfleisch 12,90 €, knuspriges Hühnerfleisch 12,90 €, Rindfleisch 12,90 €, Garnelen 15,50 €, Ente 15,90 €.","","ab 10,90 €"],["033","Gebratene Eiernudeln","Mit Gemüse. Veggie 10,90 €, Hühnerfleisch 12,90 €, knuspriges Hühnerfleisch 12,90 €, Rindfleisch 12,90 €, Garnelen 15,50 €, Ente 15,90 €.","","ab 10,90 €"]
  ]},
  {category:"Hanami Deluxe",items:[
    ["034","Gegrilltes Hähnchen · Phönix-Art","250 g gegrilltes Hähnchenfilet aus Thailand mit Zuckerschoten und saisonalem Gemüse, Reis und Deluxe-Sauce.","M, K","16,50 €"],["035","Gegrillte Ente · Ducky Duck","250 g gegrillte weibliche Barbarie-Entenbrust mit marktfrischem Gemüse in Deluxe-Sauce.","M, K","20,50 €"],["036","Teri Sake Lachs","250 g gegrillter Lachs mit 3 Garnelen, Teriyaki-Sauce und Tamarinden-Sauce.","C, E, M","25,50 €"],["037","Gegrillte Riesengarnelen","6 gegrillte Riesengarnelen mit saisonalem Gemüse, Reis und Teriyaki-Sauce.","E, M","20,50 €"],["038","Tiefblauer Ozean","3 Riesengarnelen, 2 Jakobsmuscheln und Oktopus mit gegrilltem Gemüse, Kräuterseitlingen und Tamarinden-Sauce.","E, N, M","26,90 €"],["039","Rindfleisch mit Ananas · Pineapple Gold","Rinderfiletstreifen aus dem Wok mit Zitronengras, Chili, Ananas, Sellerie, Babymais, Zuckerschoten, Tomaten, Peperoni und Zwiebeln.","L, M","20,50 €"]
  ]},
  {category:"Vegetarisch & Ramen",items:[
    ["040","Teriyaki · Tofu","Bestes Saisongemüse mit Teriyaki-Soße und Tofu.","M","13,50 €"],["041","Weißer Pilz · White Mushroom","Weißer Pilz, knuspriger Tofu und Gemüse mit Soja-Sesam-Soße.","M, L","14,50 €"],["042","Würziger Tofu","Verschiedenes Gemüse mit Zitronengras, Chili und leicht scharfem Tofu.","M","14,50 €"],["043","Vit Chay · Seitan „Ente“","Seitan-Ente, Zuckererbsen und saisonales Gemüse mit Reis und Deluxe-Soße.","D, M","16,50 €"],["044","Ga Chay · Vegan Chicken","Vegan Soy Chicken, Zuckererbsen und saisonales Gemüse mit Reis und Deluxe-Soße.","D, M","15,50 €"],["045","Würzige Signatur-Ramen-Brühe","Schweinebrühe und würzige dunkle Sojabohnen, Hühnerbrustfilet, japanische Pilze, Frühlingszwiebeln, Morcheln, Kimchi und Ei.","A, F, H","14,90 €"],["046","Miso-Ramen Brühe","Hühner- und Sojabohnenbrühe, gebratenes Hähnchen, Schweine-Charsiu, Mais, Morcheln, Frühlingszwiebeln und Ei.","A, D, F, G, M","15,50 €"],["047","Tonkotsu-Ramen Brühe","Schweine- und Hühnerbrühe, Schweine-Charsiu, Schweinefleisch, Mais, Morcheln, Frühlingszwiebeln und Ei.","A, D, F, G, M","15,50 €"],["048","Veggie-Ramen Brühe","Bestes Saisongemüse mit Teriyaki-Soße und Tofu.","A, D, F, G, M","13,50 €"],["049","Rindfleisch Ramen Brühe","Hühner- und Sojabohnenbrühe mit Rindfleisch, Pilzen, Frühlingszwiebeln, Morcheln, Kimchi und Ei.","A, F, G, M","15,50 €"],["050","Garnelen-Ramen Brühe","Hühner- und Sojabohnenbrühe mit Garnelen, Pilzen, Frühlingszwiebeln, Morcheln, Kimchi und Ei.","A, E, F, M","16,50 €"],["051","Rind-Garnelen-Ramen Brühe","Hühner- und Sojabohnenbrühe mit Rindfleisch, Garnelen, Pilzen, Frühlingszwiebeln, Morcheln, Kimchi und Ei.","A, E, F, M","16,50 €"]
  ]},
  {category:"Nigiri",items:[
    ["110","Sake · Lachs","2 Stück.","C","4,30 €"],["111","Maguro · Thunfisch","2 Stück.","C","4,90 €"],["112","Ebi · Garnelen","2 Stück.","","5,20 €"],["113","Unagi · Gegrillter Aal","2 Stück.","C","5,20 €"],["114","Hotategai · Jakobsmuscheln","2 Stück.","N","5,20 €"],["115","Vegetarische Tamago","2 Stück.","A","3,90 €"],["116","Vegetarisches Inari · Sushi","Süße Tofutasche, gefüllt mit Reis. 2 Stück.","F, M","3,90 €"],["117","Vegetarische Avocado","2 Stück.","","3,90 €"],["066","Vegetarische Oshinko","2 Stück.","","3,90 €"],["118","Sake, grüner Spargel","2 Stück.","","5,70 €"],["119","Maguro, grüner Spargel","2 Stück.","","5,90 €"],["120","Hotategai, grüner Spargel","Jakobsmuscheln, grüner Spargel. 2 Stück.","N","6,00 €"]
  ]},
  {category:"Maki & Futo Maki",items:[
    ["121","Sake · Lachs","8 Stück.","","4,30 €"],["122","Takka Tatar Sake","8 Stück.","","5,50 €"],["123","Tuna · Thunfisch","8 Stück.","","4,50 €"],["124","Takka Tatar Maguro","8 Stück.","","5,90 €"],["125","Tekka Tuna · Scharfer Thunfisch","8 Stück.","C","4,70 €"],["126","Sake Avocado · Lachs Avocado","8 Stück.","","4,50 €"],["127","Ebi · Garnelen","8 Stück.","","4,50 €"],["128","Ebi Avocado · Garnelen Avocado","8 Stück.","E","5,90 €"],["129","Tempura Maki","8 Stück.","","4,90 €"],["130","California · Surimi Avocado","8 Stück.","C, F","5,90 €"],["131","Lachshaut","8 Stück.","","4,70 €"],["132","Kappa · Gurke","8 Stück.","","4,00 €"],["133","Avocado","8 Stück.","","4,00 €"],["134","O-Shinko · Marinierter Rettich","8 Stück.","","4,00 €"],["140","Futo-Sake · Lachs","Lachs, Avocado, Gurke. 8 Stück.","C","11,50 €"],["141","Futo-Tuna · Thunfisch","Thunfisch, Avocado, Gurke. 8 Stück.","C","12,50 €"],["142","Futo-Hanami","Lachs, Thunfisch, Surimi. 8 Stück.","C","14,50 €"],["143","Futo-Tempura Chicken","Avocado, Gurke, gebackenes Hühnerbrustfilet mit Mango-Chili-Dip. 8 Stück.","A, D","11,50 €"],["144","Futo-Veggie","Tamago, Gurke, Avocado, Rucola und Frischkäse. 8 Stück.","A, G","10,50 €"]
  ]},
  {category:"Inside-Out Rolls",items:[
    ["150","California","Surimi, Avocado, Mayo. 8 Stück.","A, M","7,60 €"],["151","Sake Ava","Lachs, Avocado, Mayo. 8 Stück.","","7,60 €"],["152","Maguro","Thunfisch, Gurke, Mayo. 8 Stück.","A, C","7,90 €"],["153","Ebi","Großgarnelen, Avocado, Mayo. 8 Stück.","A, E","8,00 €"],["154","Ebi Tempura","Tempura-Garnelen, Avocado, Mayo. 8 Stück.","A, E","8,50 €"],["155","Salmon Skin","Gegrillte Lachshaut, Avocado. 8 Stück.","C","7,50 €"],["156","Unagi","Süßwasser-Aal, Avocado. 8 Stück.","C","8,50 €"],["157","Chicken","Chicken, Avocado, Mayo. 8 Stück.","","8,00 €"],["158","Spicy Tuna","Thunfisch, Gurke, Chili, Lauch, Tobiko. 8 Stück.","A, D, F","8,50 €"],["159","Spicy Tuna gekocht","Gekochter Thunfisch, Gurke, Mayo, Lauch, Chili, Tobiko. 8 Stück.","A, C, D, F","8,50 €"],["160","Spicy Ebi","Gekochte Garnelen, Gurke, Mayo, Chili, Lauch, Frischkäse, Tobiko. 8 Stück.","A, B, C, D, G, F","8,90 €"],["161","Spicy Salmon","Lachs, Avocado, Gurke, Chili, Lauch, Tobiko. 8 Stück.","A, C, D, F","8,90 €"],["162","Philly Cheese","Gurke, Avocado, Philly Cheese. 8 Stück.","C, G","8,50 €"],["164","Vegetarian Asparagus Roll","Grüner Spargel, Philly Cheese, Schnittlauch. 8 Stück.","G","8,50 €"],["165","Avocado","Avocado, Frischkäse, Sesam. 8 Stück.","L, G","7,50 €"],["166","Kappa","Gurke, Frischkäse, Sesam. 8 Stück.","L, G","7,00 €"],["167","Veggie","Kürbis, Gurke, Avocado, Rettich, Sesam. 8 Stück.","L","7,00 €"],["168","Avocado Tempura","Avocado Tempura, Frischkäse, Sesam. 8 Stück.","","8,00 €"]
  ]},
  {category:"Special Rolls & Sashimi",items:[
    ["170","Tiger & Dragon","Garnelen im Tempuramantel, Tobiko, Mango, Avocado, Mayo. 10 Stück.","A, B, C, D, F, G","18,00 €"],["171","Tuna Samurai","Gegrillter Thunfisch, Gurke, Avocado Tempura, Frischkäse. 10 Stück.","A, B, C, D, F, G","18,00 €"],["172","Nori Ebi","Knusprige Avocado, Flusskrebs-Tatar, gekochte Riesengarnelen mit Feuer. 10 Stück.","A, B, C, D","15,00 €"],["173","Hanami","Krebsfleischimitat, Avocado, Mango, Tobiko, Frischkäse, bedeckt mit Feuer. 10 Stück.","B, C, D, F, G","15,00 €"],["174","Tuna Fireworks","Surimi, Mango, Rettich, Frischkäse, ummantelt mit Feuerthunfisch. 10 Stück.","B, C, D, F, G","16,00 €"],["180","Spicy Chicken Roll","Chilimayo-Hähnchen, Gurke, außen Avocado. 8 Stück.","A, M","12,90 €"],["181","Spicy Tuna Roll","Chilimayo, Avocado, Thunfisch, Gurke, Lauch, Sesam. 8 Stück.","A, C, M, L","13,90 €"],["182","Kalani","Gegrillte Lachshaut, Avocado, Großgarnelen, Unagisoße. 8 Stück.","C, E, F, M","13,90 €"],["183","My Best Friend’s Roll","Avocado, Lachs, Spezialsoße, Kresse, Mayo. 8 Stück.","A, C, G, M","14,90 €"],["184","Hanami Extreme Special","Avocado, Lachs, Lachshaut, Tamago, Gurke, Masago, Tobiko, Unagisoße. 8 Stück.","A, C, E, F, G, M","16,50 €"],["191","Sake · Lachs Sashimi","6 Stück.","C","12,00 €"],["192","Tuna · Thunfisch Sashimi","6 Stück.","C","13,90 €"],["193","Tuna & Sake Sashimi","3 Stück Thunfisch und 3 Stück Lachs.","C","14,50 €"],["194","Tuna & Sake Sashimi groß","6 Stück Thunfisch und 6 Stück Lachs.","C","25,50 €"],["195","Lachs Tempura","Lachs, Avocado, Philadelphia, Sakura-Kresse und Spezialsoße. 10 Stück.","C, G","7,50 €"],["196","Thunfisch Tempura","Thunfisch, Avocado, Philadelphia, Sakura-Kresse und Spezialsoße. 10 Stück.","C, G","7,50 €"],["197","Bitte prüfen","Angabe auf der Originalkarte teilweise verdeckt.","","8,50 €"],["198","Ebi Tempura","Große Garnelen, Avocado, Philadelphia, Sakura-Kresse und Spezialsoße. 10 Stück.","E, G","7,50 €"],["199","Hähnchen Tempura","Hähnchen, Avocado, Philadelphia, Sakura-Kresse und Spezialsoße. 10 Stück.","G","7,60 €"],["200","Veggie Tempura","Avocado, Philadelphia, Kresse und Spezialsoße. 10 Stück.","A, D, F, G","6,50 €"],["201","Ebi-Avocado","10 Stück. Weitere Angabe bitte prüfen.","","7,50 €"]
  ]}
];
